name: syntax_sugar
description: A utilities library containing useful tools and syntax sugars.
version: 0.3.0
repository: https://github.com/aprosail/syntax-sugar
environment: {sdk: ^3.3.4}

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
